name: tests-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: make install

      - run: make lint

      - run: make test
